[build]
  publish = "dist"

  # Default build command.
  command = "yarn docs:build"
  ignore = "git diff --quiet HEAD^ HEAD services/ runtime/src/ docs/ examples/cra/src examples/query-playground/src/"
