version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/runtime"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/services/config"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/services/data"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
